# This is a basic workflow to help you get started with Actions

name: update novel

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install lxml

      - name: Run Script
        id: script
        run: |
          python novel-update-only.py
          
      - name: Commit
        if: ${{ steps.script.outputs.found_new == 'true'}}
        run: |
          git config --global user.email "107254798+ying-ck@users.noreply.github.com"
          git config --global user.name "ying-ck"
          git add ./book
          git add ./data
          git add ./booklist.json
          git commit -m "update novel"
          git push
          echo "finished"
  cleanup:
    needs: [update]
    runs-on: ubuntu-latest
    steps:
      - name:  Delete deployment
        if: ${{ steps.script.outputs.found_new == 'true'}}
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true
  # Single deploy job since we're just deploying
  deploy:
    needs: [update,cleanup]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ steps.script.outputs.found_new == 'true'}}
        uses: actions/checkout@v4
      - name: Setup Pages
        if: ${{ steps.script.outputs.found_new == 'true'}}
        uses: actions/configure-pages@v5
      - name: Upload artifact
        if: ${{ steps.script.outputs.found_new == 'true'}}
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        if: ${{ steps.script.outputs.found_new == 'true'}}
        id: deployment
        uses: actions/deploy-pages@v4

